from datetime import date
from models import MachineRecord

SEED_RECORDS = [
    MachineRecord(
        source="seed",
        source_url="https://precodemaquinaspublicas.com.br/mock/escavadeira-1",
        item_category="escavadeira hidráulica",
        item_name="escavadeira hidráulica 14 t",
        organ_name="Município Exemplo do Norte",
        municipality="Exemplo do Norte",
        supplier_name="Fornecedor Alfa",
        contract_type="compra",
        process_number="PE 12/2025",
        purchase_year=2025,
        amount_brl=895000.00,
        status="concluida",
        raw_excerpt="Aquisição de escavadeira hidráulica nova para secretaria de obras.",
    ),
    MachineRecord(
        source="seed",
        source_url="https://precodemaquinaspublicas.com.br/mock/cacamba-1",
        item_category="caminhão caçamba",
        item_name="caminhão caçamba 6x4",
        organ_name="Consórcio Intermunicipal Modelo",
        municipality="Modelo",
        supplier_name="Fornecedor Beta",
        contract_type="ata",
        ata_number="ARP 90/2025",
        purchase_year=2025,
        amount_brl=720000.00,
        validity_start=date(2025, 8, 1),
        validity_end=date(2026, 7, 31),
        status="vigente",
        raw_excerpt="Registro de preços para aquisição futura de caminhões caçamba 6x4.",
    ),
    MachineRecord(
        source="seed",
        source_url="https://precodemaquinaspublicas.com.br/mock/motoniveladora-1",
        item_category="motoniveladora",
        item_name="motoniveladora 140 hp",
        organ_name="Prefeitura de Exemplo do Sul",
        municipality="Exemplo do Sul",
        supplier_name="Fornecedor Gama",
        contract_type="compra",
        process_number="PE 44/2024",
        purchase_year=2024,
        amount_brl=1180000.00,
        status="concluida",
        raw_excerpt="Aquisição de motoniveladora para manutenção de estradas rurais.",
    ),
]
